### ISSUE TITLE
CSRF error

### ISSUE THREAD

**Issue by zaninijp** [pingidentity/pingone-sample-js#11]
I get the following error when running the python script:

```joezanini@joezanini-r python (master) $ python3 app.py
Traceback (most recent call last):
  File "app.py", line 6, in <module>
    from flask_wtf.csrf import CSRFProtect
  File "/usr/local/lib/python3.7/site-packages/flask_wtf/__init__.py", line 17, in <module>
    from .recaptcha import *
  File "/usr/local/lib/python3.7/site-packages/flask_wtf/recaptcha/__init__.py", line 2, in <module>
    from .fields import *
  File "/usr/local/lib/python3.7/site-packages/flask_wtf/recaptcha/fields.py", line 3, in <module>
    from . import widgets
  File "/usr/local/lib/python3.7/site-packages/flask_wtf/recaptcha/widgets.py", line 5, in <module>
    from werkzeug import url_encode
ImportError: cannot import name 'url_encode' from 'werkzeug' (/usr/local/lib/python3.7/site-packages/werkzeug/__init__.py)```

**Comment by hkrop** [comment]
This repo is moved to https://github.com/pingidentity/pingone-sample-python/ and this issue is fixed in[ this commit](https://github.com/pingidentity/pingone-sample-python/commit/5b214d059ee177f5254d20d8871ea8464a33d3d9)
